<?php declare(strict_types=1);

use Yireo\MagewireMiniCart\Magewire\MiniCart;

/** @var MiniCart $magewire */
?>
<div>
    <input type="hidden" wire:model="productId" />
    <button wire:click="addToCart">Add to cart</button>
</div>

<script>
    document.addEventListener('magewire:update', function (event) {
        require(['Magento_Customer/js/customer-data'], function (customerData) {
            customerData.reload(['cart']);
        });
    });
</script>
