<?php declare(strict_types=1);

use Yireo\MagewireMiniCart\Magewire\MiniCart;

/** @var MiniCart $magewire */
?>
<div>
    <ul>
        <?php foreach($magewire->cartItems as $cartItem): ?>
        <li>
            <strong><?= $cartItem->getName() ?> (<?= $cartItem->getQty() ?>)</strong>
            <button wire:click="incrementCartItemQty(<?= $cartItem->getId() ?>)">Increment</button>
            <button wire:click="decrementCartItemQty(<?= $cartItem->getId() ?>)">Decrement</button>
        </li>
        <?php endforeach; ?>
    </ul>
    <script>
        document.addEventListener('magewire:update', function (event) {
            require(['Magento_Customer/js/customer-data'], function (customerData) {
                customerData.reload(['cart']);
            });
        });
    </script>
</div>

